zuul.ignored-services: "*"
zuul.prefix:  /api
zuul.routes.organization-service: /organization/**
zuul.routes.licensing-service: /licensing/**
zuul.routes.authentication-service: /auth/**
#zuul.routes.licensestatic.path: /licensestatic/**
#zuul.routes.licensestatic.url:  http://licenseservice-static:8081
#zuul.routes.licensestatic.serviceId: licensestatic
#zuul.routes.licensestatic.ribbon.listOfServers: http://licenseservice-static1:8081, http://licenseservice-static2:8082
#ribbon.eureka.enabled: false
zuul.sensitiveHeaders: Cookie,Set-Cookie
zuul.debug.request: true
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 2500
#hystrix.command.licensingservice.execution.isolation.thread.timeoutInMilliseconds: 2
#licensingservice.ribbon.ReadTimeout: 2
signing.key: "345345fsdfsf5345"

# Zuul /routes actuator endpoint returning a 404
# It's now at /actuator/routes and needs to be enabled.
# URL: http://localhost:8084/actuator/routes
# See: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#endpoints
management.endpoints.web.exposure.include: mappings,filters,routes,refresh
#management.endpoints.web.exposure.include: "*"