service.property: "I AM A DEFAULT PROPERTY"
spring.database.driverClassName: "com.mysql.cj.jdbc.Driver"
spring.jpa.database: "MYSQL"
spring.jpa.showSql: "true"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.MySQL57Dialect"
spring.datasource.platform:  "mysql"
spring.datasource.url: "jdbc:mysql://localhost:3306/licensing_default"
spring.datasource.username: "root"
spring.datasource.password: "{cipher}1a6d087099a484013f94121ba60d15688a2307dcbff5769ee7e6ec33eae74393"
spring.datasource.tomcat.testWhileIdle: "true"
spring.datasource.tomcat.validationQuery: "SELECT 1"
redis.server: "redis"
redis.port: "6379"
signing.key: "345345fsdfsf5345"