service:
  property: "I AM A DEFAULT PROPERTY"

# @See org.springframework.boot.autoconfigure.web.ServerProperties
server:
  port: 8082

spring:
  datasource:
    platform: "mysql"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/organization_default?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=True"
    username: "root"
    password: "{cipher}1a6d087099a484013f94121ba60d15688a2307dcbff5769ee7e6ec33eae74393"
    tomcat:
      testWhileIdle: "true"
      validationQuery: "SELECT 1"
  jpa:
    database: "MYSQL"
    showSql: "true"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL8Dialect"

security:
  oauth2:
    # @see org.springframework.boot.autoconfigure.security.oauth2.resource.ResourceServerProperties
    resource:
      userInfoUri: http://localhost:8084/auth/user_authorities

redis:
  server: "redis"
  port: "6379"

signing:
  key: "345345fsdfsf5345"

management:
  endpoints:
    web:
      exposure:
        include: "mappings,refresh"
#        include: "*"
